apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
data:
  MONGO_URI: {{ .Values.configMap.mongoURI | quote }}
  APP_HOST: {{ .Values.configMap.appHost | quote }}
  APP_PORT: {{ .Values.configMap.appPort | quote }}
